version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./cinema.db:/app/cinema.db
    restart: unless-stopped
